apiVersion: v1
kind: Service
metadata:
  name: svidmint
  labels:
    app: svidmint
spec:
  type: ClusterIP
  selector:
    app: svidmint
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
